language: python

branches:
  only:
    - main
    - dev
    
virtualenv:
    system_site_packages: true

python:
  - "3.8"
# command to install dependencies

before_script: cd compilador

script:
  - sudo apt-get install -y dos2unix
  - dos2unix algoritmo.txt
  - source env/bin/activate
  - python index.py
